'use client';

import { useState } from 'react';
import { useChat } from '@ai-sdk/react';
import { usePDF } from 'react-to-pdf';
import ReactMarkdown from 'react-markdown';
import rehypeRaw from 'rehype-raw';
import styles from './create.module.css';
import catalogs from '../../../../catalogs.json';
import { parseFields } from '../../utils/templateParser';

export default function CreateDocument() {
  const [docType, setDocType] = useState(null);
  const [extractedFields, setExtractedFields] = useState({});
  const [fieldMap, setFieldMap] = useState([]);
  const [standardTerms, setStandardTerms] = useState('');
  const [isComplete, setIsComplete] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isSaved, setIsSaved] = useState(false);
  const [templateContent, setTemplateContent] = useState('');

  // Manually manage input state since the latest AI SDK moves this out of useChat
  const [input, setInput] = useState('');

  const { toPDF, targetRef } = usePDF({ filename: 'Leaseefy_Document.pdf' });

  const { messages, status, append, error } = useChat({
    body: { 
      documentType: docType?.name || "document",
      fieldMap: fieldMap,
      documentState: extractedFields 
    },
    onToolCall({ toolCall }) {
      if (toolCall.toolName === 'update_document_data') {
        const { fields, isComplete: completeStatus } = toolCall.args;
        setExtractedFields(fields);
        setIsComplete(completeStatus);
      }
    }
  });

  const isLoading = status === 'submitted' || status === 'streaming';

  const handleSelectDocType = async (type) => {
    setDocType(type);
    setExtractedFields({});
    setIsComplete(false);
    
    let localParsedFields = [];

    // Fetch the actual template content from our local API route
    try {
      const res = await fetch(`/api/template?path=${encodeURIComponent(type.local_path)}`);
      if (res.ok) {
        const data = await res.json();
        setTemplateContent(data.coverPage);
        setStandardTerms(data.standardTerms);
        
        localParsedFields = parseFields(data.coverPage);
        setFieldMap(localParsedFields);
      } else {
        setTemplateContent(`> Failed to load template from ${type.local_path}.`);
        setFieldMap([]);
        console.log('Parsed fieldMap:', []);
      }
    } catch (err) {
      setTemplateContent(`> Error loading template: ${err.message}`);
      setFieldMap([]);
    }

    setTimeout(() => {
      console.log('Parsed fieldMap:', localParsedFields);
      append({ role: 'user', content: `Hi, I would like to create a ${type.name}. Please start the interview.` });
    }, 100);
  };

  const handleInputChange = (e) => {
    setInput(e.target.value);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;
    append({ role: 'user', content: input });
    setInput('');
  };

  // Remove HTML tags for a clean markdown display
  let cleanTemplateContent = templateContent ? templateContent.replace(/<[^>]+>/g, '') : '';
  let cleanStandardTerms = standardTerms ? standardTerms.replace(/<[^>]+>/g, '') : '';

  // Replace placeholders in the template with extracted fields
  Object.entries(extractedFields).forEach(([key, value]) => {
    // If the key exists in the text as a placeholder (e.g. [Party Name]), replace it
    // We escape the key for regex in case it contains brackets
    const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(escapedKey, 'g');
    cleanTemplateContent = cleanTemplateContent.replace(regex, `<span class="${styles.flashHighlight}">${value}</span>`);
  });

  const currentDocContent = `## ${docType?.name || 'Document'}\n\n` + 
    (cleanTemplateContent || '> *Awaiting template data...*') +
    (isComplete && cleanStandardTerms ? `\n\n---\n## Standard Terms\n\n${cleanStandardTerms}` : '') +
    `\n\n---\n\n*${isComplete ? `This is a legally binding template generated by Leaseefy AI.\n\nTemplate Source: Common Paper (${docType?.name}), Licensed under CC BY 4.0.` : 'Document is currently being drafted by the AI...'}*`;

  const handleSaveToDashboard = async () => {
    setIsSaving(true);
    try {
      const res = await fetch('http://localhost:8000/documents', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ title: docType.name, content: currentDocContent }),
      });
      if (res.ok) {
        setIsSaved(true);
        setTimeout(() => {
          window.location.href = '/dashboard';
        }, 2500);
      } else {
        alert('Failed to save. Please make sure you are logged in.');
      }
    } catch (err) {
      alert('Network error while saving document.');
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className={styles.container}>
      {/* Left Panel: AI Interview Chat */}
      <div className={styles.leftPanel}>
        <h2>AI Legal Assistant</h2>
        <p style={{ color: '#94a3b8', marginBottom: '2rem' }}>
          {docType ? `Interviewing for: ${docType.name}` : 'Select a document type to begin.'}
        </p>

        <div className={styles.chatMessages}>
          {messages.filter(m => m.role !== 'system' && m.role !== 'tool' && !m.content.includes('Please start the interview') && m.content.trim() !== '').map(m => (
            <div key={m.id} className={`${styles.message} ${m.role === 'user' ? styles.userMessage : styles.aiMessage}`}>
              <ReactMarkdown rehypePlugins={[rehypeRaw]}>{m.content}</ReactMarkdown>
            </div>
          ))}
          {isLoading && (
            <div className={`${styles.message} ${styles.aiMessage}`}>
              <i>Assistant is typing...</i>
            </div>
          )}
          {error && (
            <div className={`${styles.message} ${styles.aiMessage}`} style={{ backgroundColor: '#ef4444' }}>
              <strong>API Error:</strong> {error.message}
            </div>
          )}
        </div>

        {docType && (
          <form onSubmit={handleSubmit} className={styles.inputForm}>
            <input
              type="text"
              value={input}
              onChange={handleInputChange}
              placeholder={isComplete ? "Interview complete!" : "Type your answer..."}
              className={styles.inputField}
              disabled={isComplete}
            />
            <button type="submit" className={styles.sendBtn} disabled={isLoading || isComplete}>
              Send
            </button>
          </form>
        )}
      </div>

      {/* Right Panel: Data Preview & Generation */}
      <div className={styles.rightPanel}>
        {!docType ? (
          <div>
            <h2>What would you like to create?</h2>
            <div className={styles.docSelector}>
              {catalogs.map(type => (
                <button
                  key={type.name}
                  className={styles.docTypeBtn}
                  onClick={() => handleSelectDocType(type)}
                >
                  {type.name}
                </button>
              ))}
            </div>
          </div>
        ) : isSaved ? (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', textAlign: 'center' }}>
            <h1 style={{ color: '#10b981', fontSize: '3rem', marginBottom: '1rem' }}>✓ Thank You!</h1>
            <h2 style={{ color: '#f8fafc' }}>Your document has been successfully saved.</h2>
            <p style={{ color: '#94a3b8', marginTop: '1rem' }}>Redirecting you to the Dashboard...</p>
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
            <h2>{isComplete ? 'Final Document Ready' : 'Live Document Draft'}</h2>
            
            {isComplete && (
              <div style={{ display: 'flex', gap: '1rem', marginBottom: '2rem', marginTop: '1rem' }}>
                <button className={styles.actionBtn} style={{ marginTop: 0 }} onClick={handleSaveToDashboard} disabled={isSaving}>
                  {isSaving ? 'Saving...' : 'Save to Dashboard'}
                </button>
                <button className={styles.secondaryBtn} style={{ marginTop: 0, marginLeft: 0 }} onClick={() => toPDF()}>
                  Download PDF
                </button>
              </div>
            )}

            <div className={styles.documentPreview} ref={targetRef} style={{ flexGrow: 1, overflowY: 'auto' }}>
              <ReactMarkdown rehypePlugins={[rehypeRaw]}>{currentDocContent}</ReactMarkdown>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
